### ISSUE TITLE
No reference to Redis in the documentation

### ISSUE THREAD

**Issue by nikdoof** [nikdoof/dropbot#8]
Dropbot uses Redis for its EVE API cache, if no configuration value is passed then it'll default to localhost. The eveapi storage backend for Redis in ```utils.py``` silently fails, but it means that no API calls are being cached if no Redis server is available. 

Ideally the Docker image should be updated to include either a local Redis server, or provide a sample fig config to start the required dropbot/redis containers.

**Comment by robhaswell** [comment]
Also the Redis requirement should be documented.
